import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

/**
 *
 * tailwind
 * utility classes
 * modifiers
 * custom variables
 * prefix for tailwind classes
 *
 */

const inter = localFont({
  src: [
    {
      path: "../../public/fonts/InterVariable.ttf",
      weight: "100 900",
      style: "normal",
    },
    {
      path: "../../public/fonts/InterVariable-Italic.ttf",
      weight: "100 900",
      style: "italic",
    },
  ],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
